### ISSUE TITLE
Allow randomize to put blue to the left of red.

### ISSUE THREAD

**Issue by jackdreilly** [sharkdp/parachuted-robots#2]
The puzzle is much easier if blue is always to the right of red. Allow randomizing to put blue on either side of red.

**Comment by sharkdp** [comment]
Thank you for the feedback.

> The puzzle is much easier if blue is always to the right of red

I have to disagree. The two robots are completely identical and run exactly the same program. The only way in which they differ is that one starts on the left and the other on the right. The coloring is completely arbitrary, I just chose to color the left one in red and the right one in blue.

**Comment by jackdreilly** [comment]
Apologies, you're 100% right.

**Comment by sharkdp** [comment]
No need to apologize :smile:. It's still a valid suggestion to randomize the colors just for sake of visualization

**Comment by sharkdp** [comment]
I'm going to reopen this. I think my initial intention actually was to have them randomly distributed, with equal chances of red being to the left of blue or vice versa. My randomization process is flawed:

``` purs
  p1 <- randomInt 0 maxRange
  delta <- randomInt 1 (maxRange - 1)
  let p2 = (p1 + delta) `mod` (2 * maxRange)
```

The `mod` part never takes effect...

**Comment by sharkdp** [comment]
I guess it should read

``` purs
..
  delta <- randomInt 1 (2 * maxRange - 1)
..
```

**Comment by jackdreilly** [comment]
well done!
